package com.musclehack.targetedHypertrophyTraining.exerciseBank

class Exercises {
    companion object {
        const val BB_SQUATS = "barbell_squats"
        const val LEG_PRESS = "leg_press"
        const val BB_LUNGES = "barbell_lunges"
        const val DB_LUNGES = "dumbbell_lunges"
        const val LEG_EXTENSIONS = "leg_extensions"
        const val SEATED_CALF_RAISES = "seated_calf_raises"
        const val STIFF_LEGGED_DEADLIFTS = "stiff_legged_deadlifts"
        const val LEG_CURLS = "leg_curls"
        const val STANDING_CALF_RAISES = "standing_calf_raises"
        const val HACK_SQUAT_MACHINE_CALF_RAISES = "hack_squat_machine_calf_raises"
        const val CALF_RAISE_ON_LEG_PRESS = "calf_raise_on_leg_press"
        const val CHIN_UPS = "chin_ups"
        const val CLOSE_GRIP_PULLDOWNS = "close_grip_pulldowns"
        const val MACHINE_PREACHER_CURLS = "machine_preacher_curls"
        const val STANDING_BB_CURLS = "standing_bb_curls"
        const val STANDING_DB_CURLS = "standing_db_curls"
        const val EZ_BAR_CURLS = "ez_bar_curls"
        const val SEATED_INCLINE_DB_CURLS = "seated_incline_db_curls"
        const val CONCENTRATION_CURLS = "concentration_curls"
        const val DECLINE_TRICEP_EXTENSIONS = "decline_tricep_extension"
        const val DECLINE_CABLE_TRICEP_EXTENSIONS = "decline_cable_tricep_extension"
        const val WEIGHTED_TRICEP_DIPS = "weighted_tricep_dips"
        const val CLOSE_GRIP_BENCH_PRESS = "close_grip_bench_press"
        const val CABLE_BENT_OVER_TRICEP_EXTENSIONS = "cable_bent_over_tricep_extensions"
        const val CABLE_TRICEP_PUSHDOWNS = "cable_tricep_pushdowns"
        const val PINWHEEL_CURLS = "pinwheel_curls"
        const val ONE_ARM_REVERSE_PUSHDOWNS = "one_arm_reverse_pushdowns"
        const val LOW_CABLE_KICKBACKS = "low_cable_kickbacks"
        const val FLAT_BB_BENCH_PRESS = "flat_barbell_bench_press"
        const val FLAT_DB_BENCH_PRESS = "flat_dumbbell_bench_press"
        const val DECLINE_BB_BENCH_PRESS = "decline_bb_bench_press"
        const val DECLINE_DB_BENCH_PRESS = "decline_db_bench_press"
        const val DEEP_CHEST_DIPS = "deep_chest_dips"
        const val INCLINE_BENCH_PRESS = "incline_bench_press"
        const val PEC_DECK = "pec_deck"
        const val CABLE_CROSSOVERS = "cable_crossovers"
        const val DEADLIFT = "deadlift"
        const val LAT_PULLDOWNS = "lat_pulldowns"
        const val PULLUPS = "pullups"
        const val BENT_OVER_BB_ROWS = "bent_over_barbell_rows"
        const val SEATED_CABLE_ROWS = "seated_cable_rows"
        const val ONE_ARM_DB_ROWS = "one_arm_db_rows"
        const val PULLOVER_MACHINE = "pullover_machine"
        const val KNEELING_PULLOVERS = "kneeling_pullovers"
        const val DECLINE_CABLE_PULLOVERS = "decline_cable_pullovers"
        const val HYPEREXTENSIONS = "hyperextensions"
        const val STANDING_OH_BB_PRESS = "standing_oh_bb_press"
        const val STANDING_OH_DB_PRESS = "standing_oh_db_press"
        const val SEATED_OH_BB_PRESS = "seated_oh_bb_press"
        const val SEATED_OH_DB_PRESS = "seated_oh_db_press"
        const val DB_LAT_RAISES = "db_lat_raises"
        const val LAT_RAISE_MACHINE = "lat_raise_machine"
        const val CABLE_LAT_RAISES = "cable_lat_raises"
        const val BB_FRONT_RAISES = "bb_front_raises"
        const val DB_FRONT_RAISES = "db_front_raises"
        const val LOW_CABLE_FRONT_RAISES = "low_cable_front_raises"
        const val BB_SHRUGS = "bb_shrugs"
        const val SMITH_MACHINE_SHRUGS = "smith_machine_shrugs"
        const val CABLE_SHRUGS = "cable_shrugs"
        const val TRAP_BAR_SHRUGS = "trap_bar_shrugs"
        const val DB_SHRUGS = "db_shrugs"
        const val CALF_RAISE_MACHINE_SHRUGS = "calf_raise_machine_shrugs"
        const val BB_UPRIGHT_ROWS = "bb_upright_rows"
        const val DB_UPRIGHT_ROWS = "db_upright_rows"
        const val LEG_RAISES_CAPTAIN = "leg_raises_captain"
        const val HANGING_LEG_RAISES = "hanging_leg_raises"
        const val HANGING_KNEE_RAISES = "hanging_knee_raises"
        const val DECLINE_SIT_UPS = "decline_sit_ups"
        const val KNEELING_CABLE_CRUNCHES = "kneeling_cable_crunches"
        const val REVERSE_CRUNCHES = "reverse_crunches"
        const val MACHINE_CRUNCHES = "machine_crunches"
        const val MACHINE_LYING_HIP_RAISES = "machine_lying_hip_raises"
        const val BB_WRIST_CURLS = "bb_wrist_curls"
        const val DB_WRIST_CURLS = "db_wrist_curls"
        const val LOW_CABLE_WRIST_CURLS = "low_cable_wrist_curls"
        const val REVERSE_WRIST_CURLS = "reverse_wrist_curls"
        const val WRIST_ROLLER = "wrist_roller"
        const val ROPE_CURLS = "rope_curls"
        const val RACK_PULLS = "rack_pulls"
        const val UPRIGHT_ROW_ROPE = "upright_row_with_rope"
    }
}

class Categories {
    companion object {
        const val LEGS_TITLE = "legs_title"
        const val LEGS_HAMSTRING_TITLE = "legs_hamstrings_title"
        const val LEGS_QUADS_TITLE = "legs_quads_title"
        const val CALVES_TITLE = "calves_title"
        const val BICEPS_FULL_TITLE = "biceps_full_title"
        const val BICEPS_INNER_TITLE = "biceps_inner_title"
        const val TRICEPS_INNER_TITLE = "triceps_inner_title"
        const val CHEST_MAIN_TITLE = "chest_main_title"
        const val CHEST_LOWER_TITLE = "chest_lower_title"
        const val CHEST_UPPER_TITLE = "chest_upper_title"
        const val CHEST_ISOLATION_TITLE = "chest_isolation_title"
        const val BACK_FULL_TITLE = "back_full_title"
        const val BACK_SECONDARY_TITLE = "back_secondary_title"
        const val BACK_LOWER_TITLE = "back_lower_title"
        const val SHOULDERS_TITLE = "shoulders_title"
        const val SHOULDERS_LATERAL_TITLE = "shoulders_lateral_title"
        const val TRAPS_MAIN_TITLE = "traps_main_title"
        const val ABS_TITLE = "abs_title"
        const val FOREARMS_TITLE = "forearms_title"
    }
}
